"""Add tipo_incidente table

Revision ID: 8e66d867bf47
Revises: 
Create Date: 2025-06-09 17:56:48.370545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e66d867bf47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fuentes_deteccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fuentes_deteccion_id'), 'fuentes_deteccion', ['id'], unique=False)
    op.create_index(op.f('ix_fuentes_deteccion_nombre'), 'fuentes_deteccion', ['nombre'], unique=True)
    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amenaza', sa.String(), nullable=True),
    sa.Column('tipo_incidente', sa.String(), nullable=True),
    sa.Column('severidad', sa.String(), nullable=True),
    sa.Column('prioridad', sa.String(), nullable=True),
    sa.Column('fuentes_deteccion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threats_amenaza'), 'threats', ['amenaza'], unique=True)
    op.create_index(op.f('ix_threats_id'), 'threats', ['id'], unique=False)
    op.create_table('tipo_incidente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_incidente_id'), 'tipo_incidente', ['id'], unique=False)
    op.create_index(op.f('ix_tipo_incidente_nombre'), 'tipo_incidente', ['nombre'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tipo_incidente_nombre'), table_name='tipo_incidente')
    op.drop_index(op.f('ix_tipo_incidente_id'), table_name='tipo_incidente')
    op.drop_table('tipo_incidente')
    op.drop_index(op.f('ix_threats_id'), table_name='threats')
    op.drop_index(op.f('ix_threats_amenaza'), table_name='threats')
    op.drop_table('threats')
    op.drop_index(op.f('ix_fuentes_deteccion_nombre'), table_name='fuentes_deteccion')
    op.drop_index(op.f('ix_fuentes_deteccion_id'), table_name='fuentes_deteccion')
    op.drop_table('fuentes_deteccion')
    # ### end Alembic commands ###
